### ISSUE TITLE
User gets blank page while UI5 libs load

### ISSUE THREAD

**Issue by proehlen** [propellerlabsio/meteor-ui5-website#12]
Need some sort of library or page loading indicator.

**Comment by proehlen** [comment]
Possible solution

**Comment by proehlen** [comment]
Possible solution: 

http://openui5.blogspot.com/2014/04/splash-screen.html?m=1

**Comment by proehlen** [comment]
@ChhunlyBin can you have a go at implementing the above? Do it in a new branch.  Thanks

**Comment by ChhunlyBin** [comment]
@proehlen Hello brother I don't understand the question. Do I need to implement this link  http://openui5.blogspot.com/2014/04/splash-screen.html?m=1
