### ISSUE TITLE
JSON Model Demo isn't showing any data

### ISSUE THREAD

**Issue by proehlen** [propellerlabsio/meteor-ui5-website#16]
Meteor Model and OData Model are working fine.

**Comment by ChhunlyBin** [comment]
That's very great brother it's working

**Comment by proehlen** [comment]
Hello brother,

Just to let to know, issues on github repos aren't really for social
discussion. They are also public now so may involve other people who we
don't know.

I raised the issue because it doesn't work (that's what issues are for).
If you want to comment socially or like chat, use Slack which is more
appropriate. Github issues are just for problems and discussion that is
relevant to solving those problems.

Hope you are having a good weekend,

God bless you brother,

Peter
